name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}   # 手動実行も可能

env:
  PROJECT_ID: "ivory-sanctuary-458908-v1"
  REGION: "asia-northeast1"
  SERVICE: "gpts-api-v2"
  REPOSITORY: "apps"
  IMAGE: "asia-northeast1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # WIF に必要

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      # Dockerfile 方式 (A)
      - name: Build image
        run: docker build -t "${IMAGE}" .

      - name: Push image
        run: docker push "${IMAGE}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${SERVICE}" \
            --image "${IMAGE}" \
            --region "${REGION}" \
            --platform managed \
            --allow-unauthenticated \
            --service-account gpts-api-v2@ivory-sanctuary-458908-v1.iam.gserviceaccount.com \
            --port 8080 \
            --cpu 1 \
            --memory 512Mi \
            --set-env-vars BASE_URL="https://gpts-api-v2-668935029487.asia-northeast1.run.app",OAUTH_REDIRECT_PATH="/oauth/callback",USER_TZ=Asia/Tokyo,TZ_OFFSET=+09:00,TOKEN_BUCKET=gpts-oauth-tokens,BACKUP_BUCKET=gpts-plans-backup \
            --set-secrets API_KEY=api-key:latest,OAUTH_CLIENT_ID=oauth-client-id:latest,OAUTH_CLIENT_SECRET=oauth-client-secret:latest,APP_SECRET=app-secret:latest
