# .github/workflows/deploy.yml
name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write   # OIDC 必須
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/668935029487/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: github-cloudrun-deployer-proje@ivory-sanctuary-458908-v1.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud project
        run: |
          gcloud config set project ivory-sanctuary-458908-v1
          gcloud config set run/region asia-northeast1
          gcloud --version

      - name: Deploy to Cloud Run (source)
        run: |
          gcloud run deploy gpts-api-v2 \
            --source . \
            --region asia-northeast1 \
            --allow-unauthenticated
